Started by user unknown or anonymous
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/StartTraining
[StartTraining] $ /bin/sh -xe /tmp/jenkins1779366115649984909.sh
+ sudo cat /root/MLOps/Python/main.py
+ grep keras
from keras.optimizers import Adam
from keras.models import Sequential
from keras.layers import Dense
+ sudo docker exec neuralnetwork python /home/main.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/main.py", line 7, in <module>
    dataset = pd.read_csv('Churn_Modelling.csv')
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File Churn_Modelling.csv does not exist: 'Churn_Modelling.csv'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
